language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
install:
  - pip install -r test_requirements.txt
  - pip install coveralls
script:
    coverage run --source=polling2 setup.py test
after_success:
  coveralls
